### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by CareVPN** [VPNCare/ShadowVPN-iOS#2]
### Unit Test
- [ ] add `Travis-CI`
### UI
- [x] add QRCode 
- [x] add today widget
- [ ] add logging
### Fix
- [ ] not necessary to wake program when switch off vpn in todaywidget
